# General
basepath_dir: /Users/francisco/Documents/MTI/vision_por_computadora/tarea_1
use_multithreads: True
num_threads: 6

# Dataset
dataset_dir: /Users/francisco/Documents/MTI/vision_por_computadora/tarea_1/dataset

# Images description
image_type: 'image'
channels: 3
image_width: 224
image_height: 224

# Model
num_epochs: 20
num_classes: 19
batch_size: 128
validation_steps: 14
learning_rate: 0.01
use_imagenet_weights: True
imagenet_dir: /Users/francisco/Documents/MTI/vision_por_computadora/tarea_1/weights/resnet_imagenet_045.h5

use_l2: True
weight_decay: 1600
shuffle_size: 5000
optimizer_name: 'adam'

# Snapshot
snapshot_dir: /Users/francisco/Documents/MTI/vision_por_computadora/tarea_1/snapshots/
snapshot_steps: 500
checkpoint_file: /Users/francisco/Documents/MTI/vision_por_computadora/tarea_1/snapshots/snap_snap_1
use_checkpoint: False
